name: CI CD for main merges
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: build, test and deploy spring boot app
    runs-on: ubunto-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: build and push docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-boot-for-bigginers:v1
